### ISSUE TITLE
abundance() function doesn't work

### ISSUE THREAD

**Issue by emchristensen** [weecology/portalPredictions#108]
some people are having trouble getting abundance() from portalr to work

**Comment by emchristensen** [comment]
I think I fixed this by adding the "repo" argument -- @skmorgane does the code work on your computer now? (I think we were talking about this in the context of the index.Rmd script)

**Comment by gmyenni** [comment]
Is there still a problem with the abundance function?

**Comment by emchristensen** [comment]
I think it's good now
