### ISSUE TITLE
current build failing

### ISSUE THREAD

**Issue by sdtaylor** [weecology/portalPredictions#116]
I just ran `Rscript PortalForecasts.R` and  it failed with this. The "leading minor order blah blah" is expected, but the `length(ts)` one is new and is causing the script to fail.
The last time the models were run on Travis was 5 days ago and they were fine. There has been PortalData updates since then, so I suspect some new condition has crept into the data that we haven't seen yet. 

```
There were 13 warnings (use warnings() to see them)
Making control plot forecasts 
Error in chol.default(mat) : 
  the leading minor of order 3 is not positive definite
In addition: There were 50 or more warnings (use warnings() to see the first 50)
Fitting Poisson environmental models for BA 
    Fitting Model 1 
Error: length(ts) == nrow(xreg) is not TRUE
In addition: There were 21 warnings (use warnings() to see them)
Execution halted
```

**Comment by sdtaylor** [comment]
Looks like a data issue. See the issue in PortalData.
Without the plot_table, some treatment info is getting excluded, which causes some abundance data to be dropped. The error above, `Error: length(ts) == nrow(xreg) is not TRUE`, means the length of the abundance data in the controls forecast does not match the length of the environmental data.

**Comment by gmyenni** [comment]
`Portal_plots.csv` wasn't updating. Thanks for catching that. Fixed.

**Comment by sdtaylor** [comment]
builds are working again
