### ISSUE TITLE
Move license to MIT

### ISSUE THREAD

**Issue by ethanwhite** [weecology/portalPredictions#12]
Is there a reason this repo is GPL'd? We're obligated by the DMP for this grant to use permissive licenses unless we're forced into GPL by a need to include code licensed by someone else.

**Comment by sdtaylor** [comment]
This repo started out as an exploratory personal repo, so the license stemmed from that. I think it was the first license on the list to choose from. No reason it can't be changed.

**Comment by ethanwhite** [comment]
OK, great. Thanks.

**Comment by sdtaylor** [comment]
we should  probably do this now that lots of contributions are happening. Will the MIT license work?

**Comment by ethanwhite** [comment]
> Will the MIT license work?

This is what we normally use. Is there any reason it wouldn't work?

**Comment by sdtaylor** [comment]
No reason it won't.

**Comment by sdtaylor** [comment]
done - f12064178ef3c49aa1bd21cab65be59ee95e3854
