### ISSUE TITLE
Plotly for interactive graphs

### ISSUE THREAD

**Issue by ha0ye** [weecology/portalPredictions#130]
There's a `plotly` R package that enables interactive figures in html output. Here's a [demo](https://rawgit.com/ha0ye/portalPredictions/master/docs/evaluation.html) from my fork of the repo.

I don't know what obstacles there are for any added javascript libraries on the web page or the Travis CI auto-builds, but the R code is only a few added lines. [diff](https://github.com/ha0ye/portalPredictions/commit/0a79cbfb2a69e66b879877a3c1c660e8fe0c519c#diff-921a4d7e37c9e4863ad7325cb382f9ba)

**Comment by ethanwhite** [comment]
We're in the process of moving over to Shiny to support interactive work.
