### ISSUE TITLE
Including time of censuses into data and models

### ISSUE THREAD

**Issue by juniperlsimonis** [weecology/portalPredictions#134]
Currently, the data being fed to the models do not explicitly include time when the censuses happen, and therefore the functions assume the samples come from an evenly-spaced/fully sampled data set (i.e. no missing data) and pass them to models that assume each new census is "one time step" forward. This is not true (the samples aren't evenly spaced), and so we're violating a basic assumption about the models. 

We'll definitely need to start including time in the present models moving forward and generally consider the issue of missing data. 

This is an issue that touches the data-prep code and the model code, so will likely translate into a bunch of specific tasks, but I wanted to put this on folks' radars generally now and get the conversation started about how best to approach time in the models.

**Comment by juniperlsimonis** [comment]
Specifics re: data:

The data included in the forecasting data so far cover new moons 217 to 499, which could include a total of 283 sampled new moons. However, samples have only been taken at 236 new moons , which means there is ~17% missing data. From a census date perspective, the censuses can have anywhere from 19 to 94 days between them.  It looks like the longer lags between samples have occurred throughout the history of the included time series, although there are some periods of higher frequency/length of longer lags across years (early 2000s and then again recently are when the 3-month lags happen; 1995, 1996, 2008, 2010 have no longer lags) and there is the sensible higher frequency of longer lags over the summer and winter breaks.

**Comment by juniperlsimonis** [comment]
One important question is whether we want/need to consider time in terms of new moons or Julian days. 

Although, the answer may be "both", because we may, in fact, want to run some models with one kind of time unit and some models with the other. 

It's more "true" to use Julian days of the census, especially since censuses can be as far as 11 days off from their intended new moon date, which is almost halfway between new moons, so models that allow for continuous time for a state variable, despite discrete sampling times may fare better at handling certain aspects of the dynamics. However, continuous time models can be substantially more intensive and gnarly, so we're likely going to have lots of discrete time models. Discrete time models shouldn't be iterating through at the level of day, though, as that will take FOREVER to run, so we'd likely want to do new moon as the discrete time point.

**Comment by juniperlsimonis** [comment]
In terms of data structure, in general, the ts class in R assumes equi-spaced samples, although the forecast package does have stuff built in to handle missing data. Also, the zoo package is set up to handle irregularly sampled time series.

**Comment by juniperlsimonis** [comment]
And, a question I have in terms of workflow stuff here in the context of collaborative coding, is this something that should wait until the impending merge gets finalized? I think we need to address this as soon as possible, but I don't want to mess up the current workflow.

**Comment by sdtaylor** [comment]
This will now be much easier with the latest restructuring from @gmyenni. 

Would a state space model meet all the needs you lay out? That's something we wanted to try from the get go, but then we spent a year dealing with all the infrastructure. I think a state space model could use julian days in it's structure but still injest and make predictions on our newmoon timepoints.

**Comment by juniperlsimonis** [comment]
solid! i haven't played around with the latest version yet, i'll take a look shortly and let you all know where to next specifically.

as for state space models: yes. 
for so many reasons, i'll definitely be pushing the models in that direction, but it will also be useful to retain the non-state space models for comparisons, and so we'll need to think about how we want to handle missing data in them

**Comment by sdtaylor** [comment]
There is also a more general question about the line between model improvements and new models. The current suite of models have had some minor improvements/fixes, but I think we should keep that to a minimum to allow for model comparison over time. Going from models with naive assumptions about the timeseries to ones that account for the irregular sampling may be enough to call them "new".

**Comment by juniperlsimonis** [comment]
100% agree.

**Comment by juniperlsimonis** [comment]
this has been accomplished via #212 #207 #197 #196
