### ISSUE TITLE
Reduce data manipulation in hindcasting

### ISSUE THREAD

**Issue by gmyenni** [weecology/portalPredictions#135]
How can we make better use of the provided data in hindcasting? Is there additional that we could add to the data directory to help with hindcasting?

**Comment by ethanwhite** [comment]
Agree that we should improve this, but I don't think refactoring this code should be a requirement for submitting the paper.

**Comment by sdtaylor** [comment]
hindcasting has been updated a lot since this was made and now does minimal data manipulation.
