### ISSUE TITLE
Better control of new releases

### ISSUE THREAD

**Issue by gmyenni** [weecology/portalPredictions#138]
Don't tag every new commit by weecologydeploy for release.

We already restrict it to one per day, but maybe we could control this further. Just because it would put less clutter in the Zenodo archive.

**Comment by ethanwhite** [comment]
What are the ideal conditions under which we actually want to deploy a new forecast?

**Comment by gmyenni** [comment]
When changes are made to the repo, we want to build and test, but I don't think we need to create a release and archive a forecast, right? 
I think, ideally, we would only be archiving new forecasts once a week, on Fridays, or the closest day thereafter that the build isn't broken.
So there would be a cumulative forecast for all changes made to the repo that week, rather than one for every time something is changed (most changes don't really affect the forecasts in an important way).

**Comment by ethanwhite** [comment]
:+1:
