### ISSUE TITLE
Archive forecasts externally

### ISSUE THREAD

**Issue by ethanwhite** [weecology/portalPredictions#141]
One solution to #137 is to archive the forecasts outside of this repository. This also has the advantage of producing archived forecasts that don't require digging through all of the code, etc. We've started a `forecasts` repo that is hooked up with Zenodo for other projects, so one option is switching to archiving just the forecasts themselves there.

**Comment by ethanwhite** [comment]
I know how to do this, which opens up the question of the complexities. At the moment there is a some  code in this repo that relies on the things in the `predictions` folder (most notably `compile_forecasts`). If we only store predictions externally we'd need to deal with getting that data so that the code can use it.

My current thought is to either:

1. Just leave things as they are for now
2. Keep updating the `predictions` folder in the repo, but also archive it separately.

That said, I'm open to:

3. Store all predictions outside this repo and update the code here to access that data separately.

Thoughts?

UPDATE: The easiest way to do this (that I've found so far) is to use `archive.sh` to clone the archival repository, copy the files from the predictions folder into it, add all changed files, push to the archive repo, and trigger a release. It's basically the same code as we have now, but with the clone and copy added to the front.

**Comment by gmyenni** [comment]
I don't really have a good feeling for which is better. It seems intuitive to me that the actual predictions would be here, but either way seems fine to me.

**Comment by ethanwhite** [comment]
Implemented option (2) in 4a2f8b59eeeec56a161ca37f9cf24cc58594bed8.
