### ISSUE TITLE
Add plugin figure

### ISSUE THREAD

**Issue by ethanwhite** [weecology/portalPredictions#143]
Add a figure showing the basic structure of the input and output data with an Rscript model in between. This is illustrative, so it doesn't have to include all of then necessary details in any of these steps.

**Comment by gmyenni** [comment]
Rough draft

![figure3](https://user-images.githubusercontent.com/2029124/34748600-59644300-f56b-11e7-97b2-28bc710c759c.gif)

**Comment by ethanwhite** [comment]
Great first draft. Exactly what I was thinking about. A couple of thoughts:

1. Should the top data been shown as long instead of wide? E.g., date, plots, species, tag, weight. That's how the core data is structured and since we talk about biomass showing that it isn't just counts seems useful. Or are we using a wide format as our primary input for the model scripts?
2. The R script should have a `.R` extension.
3. There is quite a bit of color. I'd personally be tempted to replace the purple background for the R script with a light grey.
4. The example model name might be confusing. This is the "naive" model right. If so let's maybe call it AR1 here.
5. Drop the 'level' column since it intuitively make sense to most folks.

**Comment by gmyenni** [comment]
![figure3](https://user-images.githubusercontent.com/2029124/35058434-2b9fa760-fb75-11e7-90b2-01ec0762867b.gif)

The data actually are wide (there is the option in the abundance function to return data as flat or crosstab, and we're using crosstab ATM). But I don't imagine they'll stay that way.

**Comment by ethanwhite** [comment]
Thanks @gmyenni - this looks great. I think we should probably go ahead and switch to long since it's more flexible. We can still have this kind 'month, species' grouped data frame but going long will let us also include things like biomass in that dataframe what most tools will find easier to process.
