### ISSUE TITLE
Evaluate forecasts for newest data quantitatively

### ISSUE THREAD

**Issue by ethanwhite** [weecology/portalPredictions#144]
Not evaluating our actual forecasts fills a little thin since our core point is the importance of doing this iteratively. We should evaluate at least the last months forecast using MSE and coverage and possibly go back further in time as well. So, basically, for the most recent data, how well was it forecast one month ago, two months ago, etc. Eventually we could do this with all of the forecasts we've made to get average performance, but just doing the most recent chunk of data seems like a good first step.

@sdtaylor - is this something we could easily modify the current hindcasting code to accomplish or would it be easier to just write this from scratch?

**Comment by sdtaylor** [comment]
This would have to be done from scratch. nothing in the hindcasting or evaluation page is currently setup to run automatically.

**Comment by ethanwhite** [comment]
> This would have to be done from scratch. nothing in the hindcasting or evaluation page is currently setup to run automatically.

Thanks. Good to know.

**Comment by sdtaylor** [comment]
were you thinking of displaying the actual numbers for this as opposed to some graphics?

**Comment by ethanwhite** [comment]
I think graphics would be fine. I was basically envisioning something like the evaluation page but for our actual past forecasts rather than the hindcasting.

**Comment by sdtaylor** [comment]
fyi I delved into this a little bit but ran into errors elsewhere in the code, which I've worked on fixing but it's taking time. I'm waiting on addressing this issue until the build errors on all our packages are sorted.

**Comment by ethanwhite** [comment]
Thanks @sdtaylor. It looks like @gmyenni may have gotten the last of the build errors straightened out this afternoon.

**Comment by gmyenni** [comment]
Yeah, everything is fine. The error with portalr currently is due to the vignette, so that shouldn't affect it's use. Is there anything else you were waiting on?

**Comment by sdtaylor** [comment]
nope, I'm good. Today is now portalPredictions day

**Comment by sdtaylor** [comment]
so far so good.

![image](https://user-images.githubusercontent.com/12282062/35170378-fe1bd60a-fd2d-11e7-8a13-e0459ca21a4a.png)

**Comment by sdtaylor** [comment]
It's working :smile: http://portal.naturecast.org/evaluation.html

**Comment by ethanwhite** [comment]
:clap:

**Comment by skmorgane** [comment]
Closed by #169
