### ISSUE TITLE
Core questions

### ISSUE THREAD

**Issue by gmyenni** [weecology/portalPredictions#150]
- core/transient
- forcastability
- data driven - process driven spectrum
- how much knowledge needed to forecast (how little can we get away with)

**Comment by juniperlsimonis** [comment]
Question development

what drives total abundance?
  -resource limitation 
  -climate
  -time lags

how much data do you need to forecast an ecological community?
  -types of dynamics
  -amount of data
  -explanatory covariates

-utility and project design
  -given a prediction of abundance, scale the field work prep

abundance more than richness
specific species (k-rats are where lots of folks work on species-level dynamics)
biomass or energy use
