### ISSUE TITLE
Figures 1 and 2

### ISSUE THREAD

**Issue by gmyenni** [weecology/portalPredictions#155]
https://docs.google.com/presentation/d/1lA9je4gTW6NzTBRg0XBIqJw_4GtxB-w50hUXO0Cf57Q/edit?usp=sharing

Are we using both figures? Just one or the other? Which is 1, which is 2?

**Comment by emchristensen** [comment]
They do kind of say the same thing.  If we have to choose, I like 2 better... The one advantage the first figure has is that the titles more or less line up with the sections of text that talk about them.  Is there a way to incorporate that in the 2nd fig (or would that make it too crowded)?

**Comment by gmyenni** [comment]
The way it is now (after some tweaking by me), is with both. Figure 1 introduces the steps as a pipeline, with those titles. Figure 2 is referred to in the CI section, so it works as a more complicated/accurate  picture of what we initially refer to as a pipeline.

**Comment by gmyenni** [comment]
Yeah, if we just use 2, we'll still have to figure out how to make it do what 1 does (link the titles to their real identities).

**Comment by emchristensen** [comment]
Oh ok, in context it makes sense why to have both. Fig 1 is more for laying out the steps in our pipeline, and Fig 2 emphasizes how Travis operates within that pipeline. 
Something still feels weird about having 2 similar figures, referenced in adjacent paragraphs in the text, and each figure only referred to once.

**Comment by gmyenni** [comment]
We'll need to decide how we're going to use them, and then go through the text and add references as much as possible. 

Another option is Figure 1a and 1b. . .

**Comment by skmorgane** [comment]
Ethan agrees the the overlap in the figures seems to make them unnecessary. I think they provide enough different info that both are necessary (especially for communicating something new and complicated like this). I like Glenda's 1a and 1b suggestion. Ethan is ok with going that route and then seeing what the reviewer response is.

**Comment by skmorgane** [comment]
I'm closing this issue to make more specific to-do issues about the figures.
