### ISSUE TITLE
package development

### ISSUE THREAD

**Issue by juniperlsimonis** [weecology/portalPredictions#159]
In thinking about how we will continue to develop and roll out new forecasting projects for specific questions (both within portal but also more broadly), I'm wondering how we leverage the coding work that's been done already to facilitate new projects. 

Really, what I'm thinking about is do we want to develop a package for forecasting work more generally? or for portal forecasting? 

I would think that lots of code that is portal related could be rolled into the portalr package, but that we might still want to have a portal forecasting package? In either case, I think there's more general code that could also be useful for folks and will help up the user-friendliness of the stuff that we're doing.

I don't necessarily think we have enough right now to warrant focusing on it in the short term, but as I build up the modeling framework from a math perspective, we're going to need to develop some new objects and approaches beyond our current capabilities, so this will be coming down the pike. 

I'd totally welcome thoughts about how best to facilitate the splitting and packaging of the code base as we develop this, as well as any insight into what kinds of stuff we'd want to include in a general forecasting package

**Comment by juniperlsimonis** [comment]
@gmyenni is there a plan for this already or have we not gotten to that point yet?

**Comment by gmyenni** [comment]
In terms of public use of Portal Forecasting, we've discussed a competition (invite folks to submit models, have competition rules, etc.). I made an issue for this #160 . I think this is a medium-long term goal (e.g. maybe at the end of the 'step 2' we discussed). 

But in terms of a generalized contribution to 'continuous analysis' and 'continuous forecasting,' I think we still need to have a discussion about the best form for that to take. Is it a package? Or is it kind of a 'template repo'?

**Comment by gmyenni** [comment]
Or maybe both? I'm envisioning that after the first paper comes out, folks will visit the repo just to get our scripts (the .travis.yml, update_repo.sh, etc) and an idea of how we put them all together. That will work fine, but we could also make generic versions with lots more instruction and all the Portal particulars removed. Also different 'choose your own adventure'(s) for which software to use at each step.

On the analysis end of things, though, a package makes a lot more sense.

**Comment by gmyenni** [comment]
https://github.com/weecology/portalcasting !!
