### ISSUE TITLE
handling missing data

### ISSUE THREAD

**Issue by juniperlsimonis** [weecology/portalPredictions#161]
currently our models ignore missing data (new moons when there was no survey) and we are not including placeholder (NA) values, which makes the models think the data are all taken from sequential surveys. this causes a few issues that we need to discuss and consider addressing for the paper.

the models that we're using take different approaches to missing data:

ESSS model (Naive1) 
has no capacity itself to deal with missing data. throws a warning and fits the forecasting model based on the longest string of continuous values.

AutoArima (Naive2)
has an internal capacity to deal with missing data, as long as the NAs are input. handles everything like a champ.

TSGLM (NB and Poisson EV)
has no capacity itself to deal with missing data. throws an error.

So, what this means is that we have one model that has an internal capacity to deal with missing values, and three that don't.

Given that we have missing values, and that we need to find a solution that will work for all of the models, one thought would be that we should interpolate the data for use with these models.

However, this creates a few issues:

1. We would artificially inflate the number of observations. 
2. We would be judging the models based on how well they predict interpolated values
3. Standard linear interpolation will generate non-integer values, which will not work for the NB and PEV models
4. interpolation generates point values from a statistical model (i.e. ignores the uncertainty it generated)
5. if we interpolate for all the models (so that they're all on the same footing) we would interpolate for one model where we didn't need to

issues # 1 and 2 are sort of part and parcel with interpolating data before a statistical analysis, lead to a false increase in precision, and could potentially throw red flags for some folks. they can ostensibly be addressed, but would require a dive into the guts of functions from the forecast and tscount packages. this isn't trivial since the ets function (used for Naive1) fits a ton of different models and does some extensive comparisons. 

issue # 3 just means that we'll need a little more rigorous approach to interpolation for the count data than what's out of the box available in the forecast package

issue # 4 is perhaps more of a "discussion point for the manuscript" for right now

issue # 5 may just be something we have to swallow for the time being. I don't see a way for us to use all four of these models without either interpolating (and so interpolating for the autoarima even though we didn't need to) or not interpolating and ignoring the missing data.

The modeling framework I'm developing is totally flexible to missing data/irregular sampling, so this won't be an issue once that rolls out, but for the interim we need to come up with an approach that we can use for all of the models and defend in the first ms.

**Comment by ethanwhite** [comment]
@skmorgane and I talked about this this morning and our initial thought was that any interpolation should be the responsibility of the individual models. The goal is to make forecasts from the data. Once choice that can be made to allow you to do so is to handle NAs by interpolation. All evaluation should be done on non-interpolated values with NAs left out (which I'm pretty sure is how it is currently handled).

If that's the right philosophy, then the infrastructure should provide data with NAs when data is missing. Any model that can't (or doesn't want to) deal with them has to include code for interpolation to convert the data into the desired form.

Given the proportion of missing months it doesn't seem like the details of interpolation are likely to make a big difference, so as a starting point linear interpolation rounded to the nearest integer seems like a reasonable approach for the three models that don't automatically handle nulls.

We're not actually talking about the models at all in the first ms, just the infrastructure, so we won't need to back up the approach there. That said, we definitely want things to look reasonable as a starting point if someone goes and digs into the code.

**Comment by juniperlsimonis** [comment]
Thanks! 

I agree that the interpolation should be the responsibility of any model that needs it. And also agree that the details of interpolation shouldn't be a huge issue here given the fraction of missing data points overall.

And roger that re: first ms not including the models at all (I haven't gotten to reviewing it yet!). That makes sense.

Yes, currently, evaluation (i.e the AIC calculation) is happening on the same set of data that are being used to fit the model, but that assumes the data are sequential and equi-spaced. 

If we add in NAs, to acknowledge the missing data, the models bomb. If we interpolate the NA data so that we have no more NAs, the models don't bomb, but now are evaluating the likelihood of the model based on the data set that includes the interpolations, which we don't want.

At the very least then, when creating the final model AIC for a given forecast, we need to restrict the data back to the raw (non-interpolated) form. That way, the different models are all being compared using the same data. This is pretty straight ahead and doable.

However, the stickier issues come up with looking within a single model, as those interpolated data are (by default) also being used to do any internal model fitting and parameter optimization. 

I haven't dug deep into this yet, but I'm not sure that we would be able to make it so that the parameter fits and internal model decision-making would be able to occur on the true observations only. 

And if it is possible, it might still be a lot of coding work to hack someone else's function, at which point we might want to consider just writing our own model functions.

**Comment by ethanwhite** [comment]
Update: @DAPPERstats is currently working on implementing interpolation for all four models to address this issue in the short-term.

**Comment by juniperlsimonis** [comment]
done with #196 #197 #207  #212 and #211
