### ISSUE TITLE
Figure 1 Modification

### ISSUE THREAD

**Issue by skmorgane** [weecology/portalPredictions#170]
@gmyenni: In thinking about the figure in the context of the text, it would be useful add some labels to explain what the string of words above the arrows and below the arrows represent. If we could add "Forecasting Pipeline Stages" above everything and "Stage Tasks and Infrastructure" below everything, I think that would help orient the reader to what they;re looking at relative to the text. I've tried to sketch what I was thinking below (not that I think anyone needs it but to practice my multi-media github usage :) )

<img width="1366" alt="paper figures 2" src="https://user-images.githubusercontent.com/2414347/35239498-a2533ab8-ff7e-11e7-93e2-a39faa171252.png">

**Comment by skmorgane** [comment]
Yeah! I added an image.....though, uh, I apparently cannot spell infrastructure.... You should also play around with what you think makes the most sense visually. I pondered putting those labels in line with their respective text bands but my thought was that it might make the figure too long. I also thought about curly brackets to show that the labels are linked (respectively) to the text above or below the colored arrows, but worried that might be too cluttered.

**Comment by ethanwhite** [comment]
Fixed by #174.
