### ISSUE TITLE
Figure 2 modification

### ISSUE THREAD

**Issue by skmorgane** [weecology/portalPredictions#171]
@gmyenni would it be possible to add a legend that links the colors to the stages in Fig 1? I was thinking something along the side with the colors and the stage names from figu 1 with a legend title of "forecasting stages"....though as I think about this, perhaps it might be better to call it "pipeline stages". Calling it forecasting stages probably implies we think all forecasts will have these stages....which they may I'm not up to making that call for all of forecasting.

**Comment by gmyenni** [comment]
I don't know how I'm doing with the use of space on this one. Also, I tried adding the Travis and Github markers to the legend, but then I don't know what the title would be.

**Comment by ethanwhite** [comment]
Fixed by #174.
