### ISSUE TITLE
Naive1's conflicting inputs

### ISSUE THREAD

**Issue by juniperlsimonis** [weecology/portalPredictions#179]
There's a conflict with the inputs to the forecast function in the Naive1 model that needs to be resolved

Currently, the call looks like

`model01=forecast(abundances$total,h=num_forecast_months,level=CI_level,BoxCox.lambda(0),allow.multiplicative.trend=T)`

the `BoxCox.lambda(0)` input generates a value of `1` which should be inputted to the `lambda` argument for the function but which is actually inputted to the `fan` argument of `forecast`, which doesn't have anything to do with the lambda for the model.

However, the desire to have a specified lambda, actually contradicts allowing for multiplicative trends. In the ets function underlying the model, if the lambda is specified, it triggers a different argument of `additive.only` to be TRUE, which short circuits the user input re: allowing multiplicative trends.

So, the question is:
Do we want multiplicative trends or a pre-specified lambda?

**Comment by gmyenni** [comment]
Thanks for digging into all this! 
Personally, I think multiplicative trends is the priority.

**Comment by juniperlsimonis** [comment]
done w #196
