### ISSUE TITLE
Model names

### ISSUE THREAD

**Issue by juniperlsimonis** [weecology/portalPredictions#180]
Currently we call the first two models "Naive1" and "Naive2", although I don't know if "naive" is a good descriptor here. 
in forecasting, the phrase "naive" is often used to mean something very base-level: that the forecast is equal to the last observation.
I would propose calling them ESSS (exponential smoothing state space) and ARIMA (autoregressive integrated moving average), allowing us the opportunity to include a naive (in the strict sense) forecast if desired.

this does bring up the more general issue of how we want to formulate model names as the suite grows, and if it's worth it to have a standard format or if we can get away with an ad hoc approach.

**Comment by gmyenni** [comment]
Yeah, we should probably formalize something here. The 2 'naive' models are actually named 'Forecast' (fore the Forecast package) and 'AutoArima.' (The real 'names' are in the predictions output files.)

As the number of models grows, especially when we host a competition, everyone's lazy naming schemes are bound to conflict with each other.

**Comment by ha0ye** [comment]
re: name conflicts - we can suggest that they be "[author or group name]-[model name]", and then they should be distinct enough. Could even do this with our models e.g. "Weecology-ESSS", "Weecology-ARIMA".
