### ISSUE TITLE
Manuscript Comments (Hao)

### ISSUE THREAD

**Issue by ha0ye** [weecology/portalPredictions#184]
*line numbers refer to the pdf version*

## General comments:

Line 5: "fundamental understanding of ecology" - this seems vague to me. What about a phrase that is more explicitly about processes/mechanisms? (I think "fundamental" could be deleted, regardless.)

Line 6: "Since ..." - I couldn't tell if this was intended to mean "Because ..." or "After ...", some rewording could help here.

Lines 6-9: The publication of stock assessments in fisheries could be another example of forecasts that are regularly made but not assessed.

Lines 12-17: The link here between assessing forecasts and "progress of ecological forecasting" can be expanded. I think there is both a specific gain in identifying and developing better models for the system of study, but also a meta-science gain in that assessing forecasts provides a blueprint for how to advance the field of ecological forecasting.

Lines 27-29: This sentence refers to changes in the state of the system, but the iterative approach could also be used to correct for, in general, process error due to an incomplete model, and not just stochastic shifts in the state of the system.

Lines 35-38: It's a bit clearer to me if the clauses are flipped, such as "For example, different hypotheses regarding the processes that drive ecological dynamics can be tested by computing the near-term forecast performance of alternative mechanistic models." 

Lines 42-45: Rather than repeat the previous sentence, this paragraph could start by introducing the idea of the "dynamic interplay" as an explicit feedback loop that mirrors the Observation-Hypothesis-Experiment-Evaluation cycle of the scientific method (but here as: Update Data-Forecast-Evaluation-Model Refinement). Having a figure for this would also help to convey the motivation behind doing iterative forecasting.

Lines 45-69: I think it could be nice to weave in a thread here about the functional overlap with reproducible data analysis, which provides additional incentive to adopt tools for reproducibility, while also enabling better science. (e.g. Lowndes et al. 2017 Nature Ecology & Evolution)

Lines 71-74: Could this sentence be moved to be to the third sentence of this paragraph? First sentence: what is portal; second sentence: data collection at portal; third sentence: why the frequent data collection at portal makes it an ideal test case for an iterative forecasting platform. [alternatively, merge it with the last sentence of the paragraph]

Figure 1 caption: "required" -> "requires". missing period for the last sentence.

Line 102: I tend to think of "component" as a tangible piece - would "aspect" or "property" work better here?

Line 103-105: I think this sentence can be deleted.

Lines 112-113: "it runs all the tasks needed to ensure that the forecasting pipeline runs from beginning to end" - the wording is a bit awkward. Maybe a bit more explicit detail? "it runs a computer script for the forecasting pipeline to produce new forecasts based on the updated data or model code"

Lines 115-117: "software" appears 4 times in this sentence...

Line 122-124: This clause was confusing with the separation between subject and verb; the details could be cut: "alternative CI services are available, such as Drone (link)" and maybe include a second example? You could also cut the prior sentence (119-120) for redundancy.

Line 135: How about rephrasing "To minimize issues with changes in software dependencies" to "To make our pipeline robust to changes in external software dependencies".

Figure 2: see comments on PR #174 

Line 148: "We use add" -> "We add"

Lines 149-153: I don't quite understand the "... as the glue that connects ..." metaphor. Is this describing that the system is autonomous and robust?

Lines 155-158: Perhaps the first two sentences here can be cut?

Line 166: the second "R" here is redundant.

Lines 172-178: This description is going to be tough for anyone not familiar with GitHub to follow along with. How about: "The data are then uploaded to the GitHub-based* Portal Data repository. By using GitHub, all changes to the data are logged via the Git version control system. Furthermore, all updates to the data are processed through "pull requests". These "pull requests" function as suggested changes to the data and trigger automated QA/QC checks. Once the checks pass, the "pull request" can be approved and the actual data repository is updated. This procedure ensures that avoidable errors do not reach the official version of the dataset."

This text seems distinct enough from the previous description of local QC checks to warrant a new paragraph.

[footnote: * Although GitHub is primarily intended to be a software development platform, we have found some of its features useful for data management.]

Line 192: CC0 should be described.

Lines 206-208: Does this mean changes to the underlying data format? It seems like this would be less of a problem with the way that the Portal Data repository is set up.

Lines 214-216: the "thorough" / "through" confusion is really throwing me off. 

Line 216-218: Could also mention that having the portalr package be separate from the forecasting code means that anyone who wants to use the data also has access to the same processing code.

Line 221-222: "New models should be easy to incorporate" - this seems to describe the ease of adding or updating models, while the prior and subsequent sentences seem to be talking about refitting the model with new data.

Lines 226-227: "main forecasting code" - is this more like a wrapper script?
Line 227: "each update" - is this update to the data, or update to the modeling code?

Lines 228-229: How important is the ensemble model? I have a ton of questions about whether it uses all the models in the platform or whether you have to specify which candidate models. (and what is the training data, etc.) It might be simpler not to mention this here, but in the discussion as a possibility for solicited models.

Line 220-232: I think this paragraph should more strongly emphasize how each model is treated as an interchangeable black box . (and how that is important for both the automation of iterative forecasts and the ensemble model)

Lines 244, 249: I tend to read "gain insight into the methods/models" as referring to understanding the behavior of the models and why they perform the way they do. It seems like here, that we're just talking about computing the forecast performance of the model. Can that be made clearer?

Figure 3: This is difficult for me to parse. If the intent is to demonstrate the "plugin infrastructure", I think it needs to be clear that the model can take any input data of the correct format, and generate forecasts of the correct format. (the folder structure of where the files are stored seems not that important here)

Lines 253-257: I think the setup here needs to emphasize the distinction here between archiving and simply making something available to the public (like with the GitHub data repository). 

Lines 273-277: These lines don't seem to add much information, and I'm not sure where the last sentence is going.

Lines 294-295: "automatically acquires and processes the newest data" - this is true for the weather info, but not for the field sampling, right?

Line 299: "allows" -> "allow"

Lines 305-307: This feels somewhat wordy. Maybe "Together, these tools provide an example ..."? 

Lines 308-325: This paragraph feels like it's going in several different directions. Since it seems to focus on the benefits of the iterative forecasting system, I think it can be merged in with the last paragraph of the discussion. That way, the paragraph about the challenges immediately follows after the description of building the system.

Lines 339-344: "Tool development to reduce the effort" should be clarified - I'm not sure if this is referring to an all-in-one platform, or enhancements to the existing components used in this example.

Lines 344-347: This last sentence went somewhere else entirely. As the next paragraph is on the expertise of the team, I think this fits in further down in a more future-looking discussion.

Line 364: It would be nice to include some suggestions on how to assemble such a team, either through acquiring expertise or building collaborations.

Lines 365-390: There's a lot of content in this paragraph. It would be easier to swallow if the topic sentence clearly delineated the points, and then those were used to organize the paragraph. For example, the first aspect mentioned on line 366 is "making accurate forecasts", but this isn't really touched on later.

I also think the thread on conservation and management could be expanded on. For instance, adaptive management has been proposed as a way to deal with unexpected or rapid changes, but requires continuous monitoring and forecasting. The iterative forecasting system facilitates that. A related idea is Management Strategy Evaluation in fisheries.

## minor editorial issues

* some references need to be straightened out
* tense isn't quite consistent (past tense throughout in the "methods" section?)
* formatting of R package names (some are monospace, others are not)
* PDF output inserts "Figure #" before the caption, so this text is duplicated. (not an issue but something to be aware of if submitting a PDF version)

**Comment by skmorgane** [comment]
thanks, Hao. A new version incorporating your suggestions and Juniper's will be showing up shortly so I am closing this issue.
