### ISSUE TITLE
Add in zero abundances for when no rodents were caught in a plot.

### ISSUE THREAD

**Issue by sdtaylor** [weecology/portalPredictions#2]
From the metadata http://www.esapubs.org/archive/ecol/E090/118/Portal_rodent_metadata.htm

There are entries with note1=2 which indicate that a plot was trapped but no rodents caught. Should account for these in the munging of abundance-gam.R

**Comment by sdtaylor** [comment]
entries where note1=2 solved by dave in PR  Gamm for hipergator #8

**Comment by sdtaylor** [comment]
There are still a few one off things lurking. 
-Some plots have (likely typos) more than one date entry per period. This will cause 2 entries to be put into the model.
-some plots are missing an entry entirely (not even a note1=2 entry). 

Both of them together make about ~21 entries total, so really not a big deal.

**Comment by davharris** [comment]
Thanks for looking into this. Now that #8 has solved the original problem, I'll create a new issue (#9) for the problems you mentioned.
