### ISSUE TITLE
environmental data gaps

### ISSUE THREAD

**Issue by juniperlsimonis** [weecology/portalPredictions#208]
Now that we're interpolating the population sizes, we need to have covariates at all of the new moons, regardless of whether or not there was a census.

The weather data file that's in the repo only has data for when there were censuses.

Given that there's a weather station and such, I might imagine there is more refined weather/environmental data available, but I'm not sure what all exists in a ready-to-use format or not.

So, my question is "do those data exist?" if yes, then "how do I get them?" and if no, then "just double checking that we're ok with using the same interpolation approach to missing covariates that we use for missing response data?"

**Comment by gmyenni** [comment]
The raw weather data is hourly, except for 77-89 which has daily max and min temps, but only multi-day precip. The weather function in portalr summarizes the data daily or monthly. Another option (to center the summaries around the new moon dates or something?) can easily be added to that function.

Or if you're thinking of doing something more specific to this repo, get_weather_data in model_functions.R is where we add the new moon codes and a lag.

**Comment by juniperlsimonis** [comment]
Thanks!
Daily summaries should totally be sufficient.
I'll dig into that function and let you know if I hit any snags.

**Comment by juniperlsimonis** [comment]
handled as part of #212
