### ISSUE TITLE
potential site https issues

### ISSUE THREAD

**Issue by sdtaylor** [weecology/portalPredictions#209]
I ran into this with someone trying to view my phenology site and it getting blocked by a firewall.

This link works: http://portal.naturecast.org

But this link has issues for most people: https://portal.naturecast.org

The 2nd one is trying to connect securely. And it gets the SSL certificate for `github.io`, but that doesn't match the domain `naturecast.org`, so most browsers will flag it as insecure. 

Another problem is when the link is shared as just a domain name, browsers will automatically prepend the http, but might also prepend https, causing the error above.  

A short term solution would be to only share the link with http prepended. The only permanent solution so far I've found is to setup a cache/load balancer thru cloudflare (like [here](https://gist.github.com/cvan/8630f847f579f90e0c014dc5199c337b) or a similar service.

**Comment by ethanwhite** [comment]
If we want `https` we can do this by moving sites to https://www.netlify.com/. This is what runs https://www.ogrants.org/ & https://www.ecodse.org/. It also builds faster than GitHub pages and provides previews for PRs.

**Comment by ethanwhite** [comment]
Attaching the info on how to do subdirectory based deploys in case we decide to do this:
https://www.netlify.com/docs/continuous-deployment/#deploy-contexts

Basically put this in `netlify.toml`:

```
[build]
  base    = "docs"
```

**Comment by ethanwhite** [comment]
I just moved us over to netlify and https seems to be working smoothly:

https://portal.naturecast.org/
