### ISSUE TITLE
Change how we handle weather data lags

### ISSUE THREAD

**Issue by gmyenni** [weecology/portalPredictions#216]
We should probably change the type of weather data that's provided in data. In future, models will want other lags besides 6 months (and won't be able to call the get weather data function if they're not written in R), and certainly the option for no lag. We should either:

1. provide the original data and let the individual model scripts deal with rearranging for lags

2. provide a file with the original data along with a couple choices of lags as additional columns

3. just provide the original data, improve the get weather data function a bit and let individual models use it to get lags, don't worry about non-R model scripts for now

Option 1 seems like it would be fine to me. . .

**Comment by juniperlsimonis** [comment]
+1 for option 1. I think that is the cleanest and provides the most flexibility. We'll just need to make sure we provide weather data that go back as far as someone might (reasonably) want to include.
