### ISSUE TITLE
Evaluation page needs updating

### ISSUE THREAD

**Issue by ethanwhite** [weecology/portalPredictions#218]
Thanks to the recent changes to model names the evaluation page needs updating in two ways:

1. We should ideally rerun the hindcasts with the new versions (and names) of the models
2. The current evaluations have a number of blank plots, no ensembles, and somehow a set of GAM panels that suggest that one or more of the changes to the models have broken things on the evaluations page.

**Comment by ethanwhite** [comment]
The lack of ensembles is due to trying to plot too many dates for the color ramps, and so only the early dates get plotted. I think this is more of a general issue in that we don't really want to plot every monthly forecast on this current graph as it's going to be too many lines. I'd probably do something like three forecasts: last month, six months ago, one year ago. This would give the general idea without overwhelming the viewer.

**Comment by sdtaylor** [comment]
I originally tried to have only 1 forecast per unique `initial_newmoon`, but it looks like that's broken now with model updates. looking into it.

**Comment by sdtaylor** [comment]
here is the plot with a larger color ramp. Using only 3 different issue dates is probably better and I'll work on that. 

![image](https://user-images.githubusercontent.com/12282062/36106098-616da6de-0fe4-11e8-896a-aaaad77daeb7.png)

For the missing data though the forecasts are just not there. The GAM model only has forecasts for those 3 months in early 2017, the AutoArima and ESS are only run for total rodents, and the Ensemble has no forecasts until april 2017.

**Comment by ethanwhite** [comment]
Thanks @sdtaylor! Let's just drop the GAM from this graph. I don't mind the blank boxes for the ARIMA and ESSS as long as the Ensemble is there.

Since you're in there changing things why don't we also free the y-axis scales so that we can see what's going on with the less common species.

**Comment by ethanwhite** [comment]
I'm going to close this based on #222 and add a new issue to replace the current hindcasts.
