### ISSUE TITLE
Newest forecasts not appearing on evaluations page

### ISSUE THREAD

**Issue by ethanwhite** [weecology/portalPredictions#220]
For some reason the evaluations page is currently only showing forecasts up through 2017-11-15.

**Comment by sdtaylor** [comment]
very likely related to #218

**Comment by sdtaylor** [comment]
actually this is because the recent sampling dates in Jan '18 and Dec '17 were incomplete, so they're getting filtered out by `portalr::abundance`

**Comment by ethanwhite** [comment]
Ah, got it. I hadn't thought about the fact that we missed trapping both times.
