### ISSUE TITLE
Author signoffs

### ISSUE THREAD

**Issue by ethanwhite** [weecology/portalPredictions#221]
When you are happy with the current ms being submitted please check you box below.

- [x] Ethan
- [x] Glenda
- [x] Shawn
- [x] Erica
- [x] Ellen
- [x] Morgan

**Comment by sdtaylor** [comment]
one minor suggestion in #224, otherwise looks great. :+1:

**Comment by ethanwhite** [comment]
Done. @DAPPERstats signed off in Slack.
