### ISSUE TITLE
Rerun hindcasts

### ISSUE THREAD

**Issue by ethanwhite** [weecology/portalPredictions#223]
With the model renaming we need to rerun the hindcasts so that they match the analysis of the forecasts. To get things to build properly we'll probably need to either replace the previous hindcast files or set up the evaluation page to only show the most recent set of hindcasts.

**Comment by sdtaylor** [comment]
:+1:

**Comment by sdtaylor** [comment]
can I just delete all the  old hindcast files?

**Comment by ethanwhite** [comment]
> can I just delete all the old hindcast files?

No objections here.

**Comment by sdtaylor** [comment]
hindcasts were updated for Ethan's reasons in this PR #225, and at least once more not long after this for other reasons.
