### ISSUE TITLE
forecast-viz.R function data

### ISSUE THREAD

**Issue by skmorgane** [weecology/portalPredictions#24]
So, I'm confused about forecast-viz.R. I see it takes obs_data and makes a time series graph with the next step prediction. I'm unclear where obs_data is coming from. Do we need a function to generate the data to feed to forecast-viz or is this already generated from PortalForecasts.R and just needs to be fed through this function to generate the graph?

**Comment by gmyenni** [comment]
I think for everything we do in this repo, we should be pulling data from PortalData, and using [DataSummaryScripts](https://github.com/weecology/PortalData/tree/master/DataSummaryScripts)  to summarize, so we always have the most updated version. forecast-viz.R is looking for data produced by [RodentAbundances.R](https://github.com/weecology/PortalData/blob/master/DataSummaryScripts/RodentAbundances.R).

**Comment by skmorgane** [comment]
Thanks!
