### ISSUE TITLE
Make website dynamic

### ISSUE THREAD

**Issue by ethanwhite** [weecology/portalPredictions#248]

**Comment by juniperlsimonis** [comment]
are you thinking about dynamic in a front-end sense (i.e. dynamic user interface) or more of in terms of the back-end only?

**Comment by ethanwhite** [comment]
Front end. E.g., select the species, models, etc.

**Comment by juniperlsimonis** [comment]
ok, cool!
unless anyone else is already actively working on this, I can start to sketch out what this could look like via shiny

**Comment by ethanwhite** [comment]
No one else is working on it. I don't think it's high up on the To Do list at the moment, but no objection to a little preliminary work as time allows.

**Comment by ha0ye** [comment]
`flexdashboard` might be a nice solution here, and integrates with shiny:
https://rmarkdown.rstudio.com/flexdashboard/shiny.html

**Comment by ethanwhite** [comment]
Here's a nice example of a forecast evaluation website from 538: https://projects.fivethirtyeight.com/checking-our-work/

**Comment by juniperlsimonis** [comment]
note for us to have solid error and warning catching within the site to keep it from breaking/posting messages to the user
