### ISSUE TITLE
tidy up calls to functions in R libraries across scripts

### ISSUE THREAD

**Issue by juniperlsimonis** [weecology/portalPredictions#256]
ideally, we want to avoid using `library(package)` calls and instead use `package::function` for all functions not loaded in base R

**Comment by juniperlsimonis** [comment]
and just so I understand how the whole image is set up (@gmyenni or @ethanwhite), I'm trying to follow the yaml file (image below). 

any package that is included in the "install-packages.R" script will be installed on the image and so can be referenced in any of the following scripts using the `::` operator, correct?

![image](https://user-images.githubusercontent.com/23511502/37539805-023d00f0-2912-11e8-9d29-6470e596fa95.png)

**Comment by gmyenni** [comment]
Yep!

**Comment by juniperlsimonis** [comment]
if a script is sourced in prepare_data.R, does it need to be sourced in later scripts?
as an example, prepare_data.R sources data_tools.R, but then so too does PortalForecasts.R

**Comment by gmyenni** [comment]
A script should be sourced in any script that uses any of it's functions. (Does that sentence make sense?) I think we don't want to rely on functions being indirectly sourced.

**Comment by juniperlsimonis** [comment]
yup! 
just to be sure then, for the example I gave, we'd want to have `source(data_tools.R)` in both prepare_data.R and PortalForecasts.R?

**Comment by gmyenni** [comment]
I think `source(data_tools.R)` doesn't need to be in PortalForecasts.R, because none of it's functions are used there. Or am I missing something?

**Comment by juniperlsimonis** [comment]
nope, you are right, there's no reason why it should have been in there to being with

**Comment by gmyenni** [comment]
There probably was at some point, long ago. Clean up time!!

**Comment by juniperlsimonis** [comment]
:broom:

**Comment by gmyenni** [comment]
Done in #295
