### ISSUE TITLE
What should happen on the website when rodent data is missing

### ISSUE THREAD

**Issue by gmyenni** [weecology/portalPredictions#258]
We are currently experiencing the unlikely event that we get a string of missing rodent data. (Data for December - February is 'missing' because they were incomplete censuses, and we remove those.) We had not accommodated for this circumstance before, but now we do (thanks to 241edab). Mislabeling in old predictions was fixed in #257.

Predictions files from [2018-01-17](https://github.com/weecology/portalPredictions/blob/master/predictions/2018-01-17forecasts.csv) to [2018-03-09](https://github.com/weecology/portalPredictions/blob/master/predictions/2018-03-09forecasts.csv) represent how we used to do it. - 12 months forward from the last datapoint.
 [2018-03-16](https://github.com/weecology/portalPredictions/blob/master/predictions/2018-03-16forecasts.csv) is how we do it now - 12 months forward from today's date, total prediction length can be longer than 12.

But, what should happen on the website? Now, on the Current Forecast page, it reports our predictions for December (because that is the first prediction made). Is that fine, or should we make sure it reports the latest month, regardless of when the first prediction actually was? (This won't be happening very often.)

**Comment by gmyenni** [comment]
First and foremost, we should handle filling data in portalr, rather than throwing those data out in incomplete months. But this will still be an issue when a month is truly missed.

**Comment by ethanwhite** [comment]
@skmorgane and I chatted this morning and we think that it should be reported for the latest month.
