### ISSUE TITLE
address the lack of forecasted weather for hindcasts

### ISSUE THREAD

**Issue by juniperlsimonis** [weecology/portalPredictions#259]
with the switch to the new weather forecast approach, we are downloading weather forecasts for use in our forecasts. this works fine for when the forecast is an actual forecast (from today) but it does not work when the forecast is actually a hindcast (from sometime last year, e.g.). 

the issue is that the site that we download from does not appear to retain its historic forecasts. they might get archived somewhere (@sdtaylor do you know?) but it's not that same url (this isn't surprising, tbh). I have poked around a bit on that web site/server and haven't found anything yet. 

we have a few different possible ways to address this issue, depending on if those forecasts are archived somewhere. 

if they are, then we can include a simple argument to `fcast_weather` to say which urls to grab based on forecasting or hindcasting. this is the ideal solution, but I don't know if it's going to be possible right now for historic data.

it not, then we have to deal with the situation where the covariate data that would have been used to make the forecast at the time (the weather forecast at the time) are different than the covariate data we end up using (some approximation of the weather forecast). in this situation, I'd suggest that we use the actual observed weather data for that time, recognizing that it likely makes the predictions better than they would have been. the other option I see would be to use some model like what we're using to forecast ndvi (a seasonal autoARIMA) to forecast weather...which introduces novel variation, and therefore seems more bad than the alternative.

all together, this makes me think we should be archiving (in some sense) the covariate forecasts we use for our forecasts. what's the best way to make that happen (@ethanwhite @gmyenni)?
it used to be that we could simply recreate the covariate forecasts from the historic covariate data, but this is not the case for the weather anymore.  

this will be an issue that we'll be able to work our way out of by archiving the covariate forecasts, as eventually we'll move beyond using this time period for hindcast evaluation, and so not having the archived data won't matter anymore. but we need some solution for the situation in the interim.

**Comment by sdtaylor** [comment]
I've looked thru the site as well and don't see any past forecasts. But I'm asking the person in charge of it.

**Comment by sdtaylor** [comment]
I emailed John Abatzoglou, who runs https://climatetoolbox.org/, and he said he has climate hindcasts going back to 1982 that aren't public, but he'd be happy to send us everything for our site and to give him a week or so.

**Comment by sdtaylor** [comment]
from John: 

> My colleague who has been doing this work just got me a script to pull all of the hindcasts in from 1982-2017. I am checking this over now for any obvious issues after which I should be able to extract you a full set of hindcasts.  Sorry for the delay.

**Comment by juniperlsimonis** [comment]
can you verify from John that we can post the data online or if we need to keep it private?
also, can you get a list of folks that we should acknowledge for the data?

**Comment by sdtaylor** [comment]
Data is in! I've asked John about the above questions and am waiting to hear back. In the meantime how would we like this formatted? I was thinking to match the current weather data:

`year, month, meantemp, precipitation, climate_model, issue_date`

**Comment by juniperlsimonis** [comment]
fantastic, thanks!
and yeah, a formatting that matches the current weather data would be great!

**Comment by sdtaylor** [comment]
i'll have a PR soon as soon as I figure out where they'll best go (asking in slack).

**Comment by sdtaylor** [comment]
from John

> Hi Shawn,
> 
> Yes, that is correct.  Feel free to share this on GitHub and the reference for this would be 
> 
> Barbero, R., J.T. Abatzoglou, and K.C. Hegewisch, 2017. Evaluation of statistical downscaling of North American Multi-Model Ensemble forecasts over western USA. Wea. Forecasting,  32, 327–341
> 
> Regards,
> 
> John

**Comment by sdtaylor** [comment]
In the meantime  here is a PR with the data #275

**Comment by juniperlsimonis** [comment]
this should all be addressed with the switch to portalcasting, which now (by default) has the option `covariates_options()$append_fcast_csv` set to `TRUE`, which appends the new forecasts to the data table `data/covariate_forecasts.csv`
#295
