### ISSUE TITLE
Total vs total

### ISSUE THREAD

**Issue by skmorgane** [weecology/portalPredictions#26]
The ensemble function generates two different ensemble models for total abundance, one for Total and one for total. This seems to be coming from the PortalForecasts.R file. The NegBinomial model and Poisson Env both call it 'total'. Everything else calls it 'Total'. If I understand this right, I think this can be handled in PortalForecasts.R by either renaming abundances$total to abundances$Total or changing all species='Total' assignments to species='total'

**Comment by gmyenni** [comment]
I changed everything to 'total.'

**Comment by skmorgane** [comment]
Great
