### ISSUE TITLE
Refactor `prepare_data.R` as a function?

### ISSUE THREAD

**Issue by ha0ye** [weecology/portalPredictions#265]
The Travis CI workflow runs through `prepare_data.R` each time, but this is overkill for end-users who want to test models, since it downloads the data each time. However, you might need an updated yaml file for the current day.

I think wrapping the existing operations into a function (or several functions) would help here:
* generate the yaml file
* download the data

It would also facilitate testing and/or later reconfiguration of the code as a package (~ #159).

**Comment by ha0ye** [comment]
Also, it helps diagnose error messages, because the function name will appear in the error message:
```
Error in function() : {error message}
```

As a script, it shows up instead as:
```
Error in eval(ei, envir) : {error message}
```

**Comment by gmyenni** [comment]
Done in https://github.com/weecology/portalcasting !
