### ISSUE TITLE
Proposed forecast csv format

### ISSUE THREAD

**Issue by sdtaylor** [weecology/portalPredictions#27]
This is the list of columns we think should be in the forecast csv file that models have to produce, and that all evaluation scripts will expect to see.   

`Date`: the date the model was run on  
`forecastMonth`: the month of a prediction  (depreciated in the future)  
`forecastYear`: the year of a prediction   (depreciated in the future)  
`newMoonID`: the new moon ID of the prediction (new moon 1 is the first sample in 1977)  
`model`: the name of the model  
`currency`: the type  of value being predicted. Valid values are:   `c('abundance','richness','biomass','energy')`

`level`: the spatial level of the site being predicted. Valid values are:   `c('All','Control','FullExclosure','KratExclosure','Plot1','Plot2',...,'Plot24')`  

`species`: the species being predicted. Value are all the rodent species codes or 'total' for the combined prediction of all species. 

`estimate`: the  mean value of the prediction  
`lowerPI`: the lower bound of the predicted 95% CI
`upperPI`: the upper bound of the predicted 95% CI    

Note that currency, level, and species are the 3 unique things which models will be compared with. ie. a model predicting `level: all, currency: abundance, species: all` will only be  compared against models making those same predictions.

**Comment by emchristensen** [comment]
I'd like to throw in a vote to make the first sample in 1977 NewMoonID 1 instead of 0 -- so it lines up with period 1

**Comment by sdtaylor** [comment]
Also up in there was whether to store all forecasts in a single file that continuously grows larger, or store them in a new file every month that it's run.

**Comment by ethanwhite** [comment]
One file will probably be easier to think about for a lot of ecology users, but I'm also not opposed to an organized multi-file version (especially if we provide a reader function).

**Comment by sdtaylor** [comment]
If using multiple files a reader function would be 2-3 lines, essentially read and combine all files within a single folder. Since all info is stored within the csv, filenames can just be whatever is relevant to us for organization. I like the multi file one better since it would be easier to accept forecasts from outside groups and to make models in a different language than R. I'm not sure which one is preferable for archiving in figshare.

**Comment by gmyenni** [comment]
I added the moon number and currency to [PortalForecasts](https://github.com/weecology/portalPredictions/blob/master/predictions/PortalForecasts.csv). It looks like the moon numbers lined up correctly. Let me know what you think. I can also separate these back out into separate files if we decide to do it that way.

**Comment by ethanwhite** [comment]
@sdtaylor makes a compelling argument. I'm +1 for the multi-file approach.

**Comment by gmyenni** [comment]
New forecasts are going in as separate files.

**Comment by sdtaylor** [comment]
In the wiki https://github.com/weecology/portalPredictions/wiki/forecast-file-format
