### ISSUE TITLE
Figure 1 cleanup

### ISSUE THREAD

**Issue by gmyenni** [weecology/portalPredictions#272]

**Comment by gmyenni** [comment]
![portalforecastingfigure1](https://user-images.githubusercontent.com/2029124/42105192-ad61c7fa-7b8c-11e8-9e90-2eb8b97afe94.png)

I increased the size of the icons, added A and B labels, and added an arrow for model improvement and new models.

**Comment by ethanwhite** [comment]
Looks great. I'd say go ahead and push the update.

**Comment by ethanwhite** [comment]
Associated PR merged.
