### ISSUE TITLE
add a few more examples of ecological forecasts occurring on short time scales (daily to quarterly)

### ISSUE THREAD

**Issue by ethanwhite** [weecology/portalPredictions#284]
If we could find one more example of each that would be useful. Resolving this would just require links to two papers on daily, weekly, or quarterly ecological forecasting.

**Comment by skmorgane** [comment]
I'm working on this one.

**Comment by skmorgane** [comment]
At daily scales, ecological forecasts predict the occurrence of environmental issues like toxic algal blooms (Stumpf et al., 2009) and pollen (Prank et al 2013).  At sub-annual scales, forecasts are
used to predict the stocks of fisheries (NOAA, 2016) and the probability of coral bleaching events (Liu et al 2018).

@article{liu2018predicting,
  title={Predicting Heat Stress to Inform Reef Management: NOAA Coral Reef Watch's 4-Month Coral Bleaching Outlook},
  author={Liu, Gang and Eakin, C Mark and Chen, Mingyue and Kumar, Arun and De La Cour, Jacqueline L and Heron, Scott F and Geiger, Erick F and Skirving, William J and Tirak, Kyle V and Strong, Alan E},
  journal={Frontiers in Marine Science},
  volume={5},
  pages={57},
  year={2018},
  publisher={Frontiers}
}

@article{prank2013operational,
  title={An operational model for forecasting ragweed pollen release and dispersion in Europe},
  author={Prank, Marje and Chapman, Daniel S and Bullock, James M and Belmonte, Jordina and Berger, Uwe and Dahl, Aslog and J{\"a}ger, Siegfried and Kovtunenko, Irina and Magyar, Don{\'a}t and Niemel{\"a}, Sami and others},
  journal={Agricultural and Forest Meteorology},
  volume={182},
  pages={43--53},
  year={2013},
  publisher={Elsevier}
}

**Comment by ethanwhite** [comment]
Thanks @skmorgane! I just pushed an update to the PR with these additions.
