### ISSUE TITLE
Add description of how to add a new model

### ISSUE THREAD

**Issue by ethanwhite** [weecology/portalPredictions#286]
> L290: The idea of “plugin infrastructure” is important, but a bit vague. Seems
like a good place to point readers to documentation on exactly what you mean
here and how to plug new things in.

This is a good point and we should have a clear description of how to do this in the repo. It should be on a stand alone page somewhere so that it can be linked to directly.

**Comment by juniperlsimonis** [comment]
There's already some solid stuff up in the repo.

In the general README file, there's a section "How to add a new model" and it links to the forecast file format wiki (https://github.com/weecology/portalPredictions/wiki/Forecast-file-format)

Is that sufficient info or do we need it more detailed? 

I totally get wanting it to be a standalone page (so not part of the README, right?).  Should I just plunk that text from the README into a new markdown doc?

**Comment by ethanwhite** [comment]
Yeah, I think if the README is fully sufficient then lets just move that text to it's own page (either a wiki page or a markdown doc) and link to it from the README.

**Comment by juniperlsimonis** [comment]
ok, i just created a new branch and PR with the updated README that just links to a new [Adding a new model wiki page](https://github.com/weecology/portalPredictions/wiki/Adding-a-new-model).

**Comment by ethanwhite** [comment]
Thanks! Closed by #289 and the creation of the new wiki page.
