### ISSUE TITLE
Add dynamic reporting of model-data comparisons 

### ISSUE THREAD

**Issue by ethanwhite** [weecology/portalPredictions#287]
We currently show direct model-data comparisons each month on Rodent Report, but don't show dynamic versions of this comparison (just the prior month). It would be good to add something showing these comparisons over time to the Evaluation page.

(Suggested by a reviewer at MEE)

**Comment by gmyenni** [comment]
Moving to https://github.com/weecology/portal-forecast-web/issues/9
