### ISSUE TITLE
write predictions file compiler

### ISSUE THREAD

**Issue by skmorgane** [weecology/portalPredictions#29]
We need a function that reads all the files in the predictions folder and makes one dataframe from all the files

**Comment by sdtaylor** [comment]
so far so good #30

**Comment by skmorgane** [comment]
I have added the compiler code to the viz_maincode. It returns 27 warnings and only reads in the predictions made on 1/6/17. We need to see why it is failing on all the other files (or if I'm doing something wrong)

**Comment by sdtaylor** [comment]
Woops, that code wasn't ready yet. I was still having issues with reading and checking the dates.

**Comment by skmorgane** [comment]
compile_forecasts() is doing a lot better! Nice work. Looks like its flagging:
1. ./predictions/2015-12-12_predictions from 2015-12-11.csv
2. ./predictions/2017-01-27allforecasts.csv
3. ./predictions/2017-01-27Controlsforecasts.csv
4. ./predictions/2017-1-6Allforecasts.csv
5. ./predictions/2017-1-6Controlsforecasts.csv

Per the conversation on Slack (just moving the highlights here where they'll be easier to find)- the January forecasts are flagging because the date column heading is lowercase for those but upper case ('Date') for all the other .csv files. 

the other file, as Glenda noted, is Dave's first forecast. It's format is completely different from everything else. Let's ignore it for the time being. We can work on getting it integrated later.

**Comment by sdtaylor** [comment]
all the January 2017 files are now loading correctly. I'm going to update compile_forecasts() to also convert date to a date format using as.Date(). At the moment this will also make it reject all the 2016 forecasts, since they're in the format MM/DD/YY and should be YYYY-MM-DD

**Comment by skmorgane** [comment]
Great, thanks.
Didn't we already do all this last week? There's a commit from Glenda last week that shows she fixed this, but everything seems to have reverted to the older format (both the date vs Date and the date formats). Have I had a stroke or something?

**Comment by sdtaylor** [comment]
No stroke! They went to the correct YYYY-MM-DD format in e761ecf and then back again to MM/DD/YY in dba5af3

**Comment by sdtaylor** [comment]
This is working pretty good now.
