### ISSUE TITLE
do we need a git ignore file?

### ISSUE THREAD

**Issue by skmorgane** [weecology/portalPredictions#31]
.Rhistory seems to be under version control. Am I wrong to think that we don't want that?

**Comment by gmyenni** [comment]
Added one

**Comment by skmorgane** [comment]
thanks! oh, and the uggh commit was simply the .Rhistory thing caused me to have a repo conflict, which without Ethan to advise me led me down a series of magical git incantations that never seemed to work, until I lost faith, put in the "ugh' committ message because what were the odds it would work this time and of course, it worked.
