### ISSUE TITLE
"No such file or directory"

### ISSUE THREAD

**Issue by davharris** [weecology/portalPredictions#32]
When I run line 16, I get the following:

```
>source("~/PortalData/DataSummaryScripts/RodentAbundances.R")
Error in file(filename, "r", encoding = encoding) : 
  cannot open the connection
In addition: Warning message:
In file(filename, "r", encoding = encoding) :
  cannot open file '/Users/davidharris/PortalData/DataSummaryScripts/RodentAbundances.R': No such file or directory
```

My PortalData directory matches the Master branch of [the repo](https://github.com/weecology/PortalData). Looks like it doesn't have a "DataSummaryScripts" directory or a "RodentAbundances.R" file.

Any idea where I can find those?

**Comment by sdtaylor** [comment]
Those are from the [portal data rep](https://github.com/weecology/PortalData). Part of the PortalForecasts script, or a separate script, need to sync up the data before running the models.

**Comment by davharris** [comment]
Right. I have that repo. The file doesn't exist on the master branch (neither does the enclosing folder).

**Comment by emchristensen** [comment]
That file got moved to a new repo, PortalDataSummaries.  We decided that we should probably separate scripts for messing with data from the data repo itself.

**Comment by davharris** [comment]
Okay, thanks.  I think the directory structure could be improved though?  Right now, the script refers to 

`~/PortalData/DataSummaryScripts/RodentAbundances.R`

This raises a few issues from my perspective:

* It seems to put the `PortalDataSummaries` repository inside the `PortalData` repository. I think that having one repository inside of another one is probably asking for trouble (unless we tell Git to ignore the Summaries repo when it's looking at the Data repo).

* The `PortalDataSummaries` repository is lives in a folder called `DataSummaryScripts`. Keeping the names consistent would make them easier to keep track of.

Could we move the `DataSummaryScripts` folder to live alongside `PortalData` instead of inside it and rename it to match the repository? Or maybe there's another good solution? Thanks again.

**Comment by emchristensen** [comment]
I believe PortalDataSummaries is its own repository -- there is a DataCleaningScripts folder inside PortalData, but that's just code we use to clean and error check new data being appended.  The script you're talking about should just refer to ~/PortalDataSummaries/RodentAbundances.R

**Comment by davharris** [comment]
Okay, looks like we're on the same page. I'll submit a PR. Thanks for working through this with me.

**Comment by sdtaylor** [comment]
Can we just copy the PortalDataSummaries repo here into PortalPredictions? I'd rather not have dependencies here based on stuff in another repo that could change. I suspect there is a way in git to link the DataSummaries repo and periodically incorporate any updates from it.

**Comment by davharris** [comment]
Like a subtree or submodule? 

Dave

**Comment by sdtaylor** [comment]
Yes, one of those two looks promising.

**Comment by ethanwhite** [comment]
In my experience things like submodules and subtrees are *very* difficult to manage for folks without advanced git backgrounds (and annoying for those with them), so I don't think they are a good fit for this project.

I thought our goal was to introduce a dependency with `PortalDataSummaries` for DRY purposes. Are we having issues with `PortalDataSummaries` changing in a way that breaks things for this project? If so we should collectively chat about that.

The ultimate goal is to make `PortalDataSummaries` a package that can be used here and elsewhere.

**Comment by sdtaylor** [comment]
No issues yet. But it's potentially an issue down the road. I didn't know `PortalDataSummaries` was going to be packaged, so that's definitely the better solution.
