### ISSUE TITLE
compute scaling

### ISSUE THREAD

**Issue by juniperlsimonis** [weecology/portalPredictions#328]
we're running out of compute capacity for easy implementation on Travis and need to move things to a more future-facing solution that will allow parallelization of lots of computation

**Comment by ethanwhite** [comment]
This has now been broken out into a number of different issues under the [Infrastructure](https://github.com/weecology/portalPredictions/issues?q=is%3Aissue+is%3Aopen+label%3Ainfrastructure) tag.
