### ISSUE TITLE
Investigate more secure GitHub authorization on HiperGator

### ISSUE THREAD

**Issue by ethanwhite** [weecology/portalPredictions#338]
Credentials are currently stored as plaintext in the cronjob. Only the user can see them, but there should be a better way to do this and ideally one that allows sharing the credentials across multiple users.

One possible option would be store on disk in a directory that has read permissions for all of the users that need be be able to deploy things back to GitHub.

**Comment by henrykironde** [comment]
Note: Also create ticket to the `HiperGator` folks to look into the setup in-terms of Security and possibility of disclosing the credentials based on our propbosed approach.

**Comment by henrykironde** [comment]
credentials are secure
