### ISSUE TITLE
Notifications for cronjobs that don't run

### ISSUE THREAD

**Issue by ethanwhite** [weecology/portalPredictions#340]
We want to make sure that forecasts are happening every week. Right now we get positive confirmation if they work, but not a warning if they don't.

**Comment by henrykironde** [comment]
We have sent an email to the folks at the `Hipergator` to ensure that there won't be any need to make updates incase the deamon server is down. They do back up cron on daemon but a clarification would help us.

**Comment by ethanwhite** [comment]
Alex confirmed that things will keep running barring the complete loss of the server. We will be notified in the event that the server dies or they have to take it off-line for other reasons.
