### ISSUE TITLE
Cleanup archive_highpergator

### ISSUE THREAD

**Issue by ethanwhite** [weecology/portalPredictions#345]
This was originally designed to just be a direct clone of the Travis. Make it actually tailored to HPG.

* Remove TRAVIS_EVENT_TYPE  variable usage
* Try to reduce redundancy generated by archiving to two locations

**Comment by henrykironde** [comment]
This may be straight forward. I think we can go over it in our next meeting

**Comment by henrykironde** [comment]
covered in #358
