### ISSUE TITLE
Design breakdown for modeling + testing + website generation

### ISSUE THREAD

**Issue by ethanwhite** [weecology/portalPredictions#346]
Currently all happening on Travis & Hipergator. Need to think about the best way to partition these tasks with the goal of making the pipeline both understandable and robust.

**Comment by gmyenni** [comment]
After talks with @juniperlsimonis and @henrykironde , planned design is as follows:

- Hipergator - Modeling
  - Dry run (#364)
    - Fast modeling
    - Tests build 
    - Test modeling (tests/testthat/test-successful_forecasts.R)
  - Real run
    - Full modeling
    - Test modeling (tests/testthat/test-successful_forecasts.R)
    - Test committing (tests/testthat/test-forecasts_committed.R) (#363)

- Travis - Generic testing
  - tests/testthat/test-travis.R
  - Test website dependencies
  - Test PRs

- Website
  - New separate repo (#247)
  - Dynamic (#248)

Beginnings of restructure are in #362
