### ISSUE TITLE
Prevent archiving if testing fails on HiperGator

### ISSUE THREAD

**Issue by ethanwhite** [weecology/portalPredictions#349]

**Comment by ethanwhite** [comment]
Could relate to #346.

**Comment by henrykironde** [comment]
try 
 || exit 1  on 
`singularity run ../portal_predictions_latest.sif Rscript tests/testthat.R > ../testthat.log 2>&1`

ref: https://unix.stackexchange.com/questions/309339/how-to-exit-a-shell-script-if-one-part-of-it-fails#309344
