### ISSUE TITLE
Remove commented out tests

### ISSUE THREAD

**Issue by henrykironde** [weecology/portalPredictions#361]
https://github.com/weecology/portalPredictions/blob/master/tests/testthat/test-new_forecasts.R#L9
As we want to test predictions, we have a set of these commented out tests from wayback. 
Should we go ahead and remove(clean up) these tests?

What other tests do  you recommend to include in portalPredictions?

**What we discussed was**
 
- Are there tests in Portalcasting that we could include in Portal prediction (mainly on the expected file structure).

- Moving the website to a new repository. Have tests related to the website(still in discussion)

**Comment by gmyenni** [comment]
Done #362
