### ISSUE TITLE
Add a dry test run a few hour before the actual HiPerGator run

### ISSUE THREAD

**Issue by henrykironde** [weecology/portalPredictions#364]
From the discussion:

**Design:**
- Create seperate test files.
A dry run test file should contain tests that will inform us of a failure hours before the actual production run starts.
- We  shall also have tests that run specifically on Travis and test that run only on the HiPerGator.

- We could probably use a separate cron job set a few hours and with a dry Run script

**Comment by ethanwhite** [comment]
* Just run ARIMA models (@juniperlsimonis's suggestion)
* Run daily

**Comment by gmyenni** [comment]
This is happening now. Are we happy with it running daily?

**Comment by ethanwhite** [comment]
I think daily is useful, but it would be nice to figure out a way a way to just get notified when it goes wrong. I'm not sure how to do that within the same crontab setup.

**Comment by gmyenni** [comment]
I was thinking that too! Just a notification when it fails/errors. Should I close this issue and open a new one for that?

**Comment by ethanwhite** [comment]
Sounds good to me!
