### ISSUE TITLE
Store less in main Zenodo archive

### ISSUE THREAD

**Issue by ethanwhite** [weecology/portalPredictions#375]
We are currently archiving full model objects. They are large. This slows setup substantially, won't be sustainable, and aren't necessary for most folks. Start archiving just the key pieces that are useful for most applications (probably following EFI standards).

## Options

1. Only archive `*_model_fits.json` objects locally on HiPerGator + backup
2. Archive only to the `forecasts` repo/Zenodo where they aren't currently downloaded

Option (2) seems feasible for now and keeps archiving full objects.

## Checklist for Option 2

- [x] Modify `archive_hipergator.sh` to copy files from new `fits` directory to `forecasts/portal/` along with those from the `casts` directory
- [x] Modify `portal_weekly_forecast.sh` to not delete the `portalPredictions` directory (where the `fits` directory will be located). Instead `fetch` and the `reset --hard upstream/master`. We could `pull` but risks a history change breaking things (see note below).
- [x] Add `fits` directory to `.gitignore`
- [x] Move current `*_model_fits.json` objects from `casts` to `fits` on HiPerGator
- [x] Remove `*_model_fits.json` objects from `casts` in `portalPredictions`
- [x] Merge https://github.com/weecology/portalcasting/pull/179
- [x] New `portalcasting` release
- [x] Update `portalcasting` Docker container
- [x] Move any new `*_model_fits.json` objects added by weekly forecasts before `portalcasting` update
- [ ] Remove `*_model_fits.json` from repo history (Blocked by https://github.com/weecology/portalcasting/pull/179 since news `_model_fits.json` objects will current still be added. Only want to rewrite the history once. Need to make sure this doesn't break the update to `portal_weekly_forecast.sh` since a basic `pull` won't work with history rewrite). This isn't essential since the archive doesn't care about the history, but it will make the repo itself much more light weight.

**Comment by gmyenni** [comment]
remaining low-priority item in #398
