### ISSUE TITLE
Move to plugin structure for models

### ISSUE THREAD

**Issue by ethanwhite** [weecology/portalPredictions#49]
* Each model should be in it's own R script
* All of those scripts follow a set of rules that allows them to be run by core code
* All models are stored in a `models` directory
* Any new model can be added by adding a new file that follows those rules to the `models` directory

**Comment by sdtaylor** [comment]
Here's some simple code that can do this based off the hindcasting code. I know @ethanwhite  mentioned that the `system` statement has issues on windows, but I can't think of a better way so far. Perhaps do the same thing in Python?

```
PortalDataSummaries::download_observations()
model_dir = './models'
model_file_list = list.files(model_dir, full.names = TRUE)
for(model_file in model_file_list){
    status = try(system(paste('Rscript', model_file, sep=' ')))
    if(class(status)=='try-error'){
        #Log or print a warning about a failed model
    }
}
