### ISSUE TITLE
Replace local `download_observations` with PortalDataSummaries

### ISSUE THREAD

**Issue by ethanwhite** [weecology/portalPredictions#63]
There is currently a local version of `download_observations` in `forecast_tools.R`. This should be replaced to calls with the same function in `PortalDataSummaries`. I haven't yet checked if the two functions are identical.

**Comment by sdtaylor** [comment]
they are identical

**Comment by ethanwhite** [comment]
Great. Thanks. Morgan is working on this one (once we unbreak PortalDataSummaries on Windows).

**Comment by ethanwhite** [comment]
Closed by 7e071c19ee0c797684b60836c0e4d64206f9133a.
