### ISSUE TITLE
tscount package no longer supported by cran

### ISSUE THREAD

**Issue by skmorgane** [weecology/portalPredictions#73]
We need to check if tscount is being maintained elsewhere (and that's where we should get it from) or if it is abandoned code

**Comment by skmorgane** [comment]
On R-Forge, the link to the package's SVN repo suggests the maintainer's most recent commit was in December.

**Comment by ethanwhite** [comment]
Looks like this project has probably been abandoned. We're currently install successfully from R-Forge, but we should start to look for alternatives or build out our own versions of these models.

**Comment by ethanwhite** [comment]
Recount is now back on CRAN as of a few days ago (discovered by @ha0ye; thanks Hao!)
