### ISSUE TITLE
testit package mystery

### ISSUE THREAD

**Issue by skmorgane** [weecology/portalPredictions#74]
The testit package is being loaded by PortalForecasts.R. Why? And if necessary, can we convert to testthat so we are only using one testing package.

**Comment by ethanwhite** [comment]
Looks like @gmyenni added it here:
https://github.com/weecology/portalPredictions/commit/fed7a3c0c8e6e43fd2cb647320fd8498158520ed

**Comment by gmyenni** [comment]
Oh, that's where `has_error` comes from, which is used in some of the models to replace aics.

**Comment by skmorgane** [comment]
Is it something we can so equally well with the testthat package? Just seems like having two separate testing packages for a codeset is overkill (and is just one more package that needs to be installed, updated, etc)

**Comment by gmyenni** [comment]
I couldn't find any testthat functions that work that way. I used tryCatch. It's less readable, but doesn't require loading any packages. #76
