### ISSUE TITLE
add new columns

### ISSUE THREAD

**Issue by sdtaylor** [weecology/portalPredictions#79]
Right now if a forecast is made it makes a bunch of entries like this  

```
        date forecastmonth forecastyear NewMoonNumber  currency    model level species estimate  LowerPI  UpperPI
1 2017-04-28             4         2017           493 abundance Forecast   All   total 168.4278 93.70367 243.1519
2 2017-04-28             5         2017           494 abundance Forecast   All   total 176.7162 71.99319 281.4392
3 2017-04-28             6         2017           495 abundance Forecast   All   total 185.0046 54.05994 315.9492
4 2017-04-28             7         2017           496 abundance Forecast   All   total 193.2929 37.75832 348.8276
5 2017-04-28             8         2017           497 abundance Forecast   All   total 201.5813 22.21281 380.9498
```
That was from April, 2017. In May there will also be forecasts for new moons 494-497 and where currency, model, level, and species are all the same. These can coexist because they have different dates from the models being run a month apart.   
But when I run the hindcasting scripts, a bunch of different forecasts will be run on the same day and  thus have the same date (and same everything else), but their difference is they have different starting newmoons, and at the moment there is no way to tell those apart. 

At the moment the only way I can think to fix this is add a new column called "start_newmoon" or something like that, and possibly rename date to something more descriptive. Any thoughts?

ps. I think this may be the last obstacle to overcome for hindcasting.

**Comment by gmyenni** [comment]
In the forecasts, they can also be differentiated because they are in separate files. How will the hindcasts be stored? If it's analogous to forecasting, each set of hindcasts with the same 'starting newmoon' would be in one file. Hindcasts with a different 'starting newmoon' would be in a separate file, even though they are run on the same date. The 'starting newmoon' for that whole file can then be inferred from the earliest forecastmonth/NewMoonNumber included in that file. Would that be a convenient enough way to differentiate them?

**Comment by sdtaylor** [comment]
Yes, that might work. But the filenames are only encountered in `compile_forecasts()`, so that function would still have to add an other column of starting_newmoon so that everything else can tell the difference between them.

**Comment by sdtaylor** [comment]
From today's meeting we'll be adding three new columns to deal with this.

`fit_start_newmoon`: the newmoon which the training data starts
`fit_end_newmoon`: the newmoon which the training data ends
`initial_newmoon`: the  newmoon immedietly prior to the first forecast of the model. This will commonly be the same as `fit_end_newmoon` but could potentially be different for more complex models.

**Comment by sdtaylor** [comment]
Should we go thru and add these columns manually (or with a quick script) to all the old forecasts? Alternatively I could write a function that adds them automatically based on what newmoons are in the forecast.

**Comment by sdtaylor** [comment]
From todays meeting, we will deal with the old forecasts later.

**Comment by sdtaylor** [comment]
#81
