### ISSUE TITLE
missing/duplicate plots?

### ISSUE THREAD

**Issue by davharris** [weecology/portalPredictions#9]
Shawn said (in #2):

```
There are still a few one off things lurking. 
-Some plots have (likely typos) more than one date entry per period. This will cause 2 entries to be put into the model.
-some plots are missing an entry entirely (not even a note1=2 entry).

Both of them together make about ~21 entries total, so really not a big deal.
```

**Comment by emchristensen** [comment]
I've looked into these issues, there are definitely some problems that can't be resolved (the database accurately reflects what is written on the sheets, for better or worse).  However you should be able to use the Portal_rodent_trapping.csv to get a single date each plot was trapped each period, and whether or not each plot was trapped.
